name: Helm Chart Build and Publish

on  :
  push             :
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps  :
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'

      - name: Install Helm Chart Releaser
        run : |
          curl -fsSL -o /tmp/get-helm-releaser.sh https://raw.githubusercontent.com/helm/chart-releaser/master/scripts/get-helm-releaser
          chmod +x /tmp/get-helm-releaser.sh
          /tmp/get-helm-releaser.sh
          mv helm-releaser /usr/local/bin/helm-releaser

      - name: Package Helm Chart
        run : |
          cd charts/adguard-home
          helm package .

      - name: Helm Chart Releaser
        run : |
          helm-releaser release \
            --config .helmreleaser.yaml \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --commit-author "Your Name <your.email@example.com>" \
            --commit-message "Release {{ .Version }}"